namespace BlogApi.Shared.Enums;

public enum ERROR_CODE
{
    // Códigos Generales (1-99)
    UNKNOWN_ERROR = 1,
    INTERNAL_SERVER_ERROR = 2,
    SERVICE_UNAVAILABLE = 3,
    IO_ERROR = 4,
    FILE_SYSTEM_UNAUTHORIZED_ACCESS = 5,

    // Errores de Validación los datos (100-199)
    GENERAL_VALIDATION_ERROR = 100,
    MISSING_REQUIRED_FIELD = 101,
    FIELD_NOT_REQUIRED = 102,

    // Errores de Autenticación y Autorización (200-299)
    GENERAL_AUTH_ERROR = 200,
    INVALID_CREDENTIALS = 201,
    TOKEN_EXPIRED = 202,
    INVALID_TOKEN = 203,
    UNAUTHORIZED = 204,
    FORBIDDEN = 205,
    NOT_ENOUGH_PERMISSIONS = 206,
    NOT_ENOUGH_CREADENTIALS = 207,
    INVALID_OPERATION = 208,
    INVALID_AUTH_OPERATION = 209,

    // Errores de Base de Datos (300-399)
    GENERAL_DATABASE_ERROR = 300,
    DATABASE_CONNECTION_ERROR = 301,
    QUERY_EXECUTION_ERROR = 302,
    RECORD_NOT_FOUND = 303,
    QUERY_TIMEOUT = 304,
    UNABLE_TO_UPDATE_RECORD = 305,
    UNABLE_TO_CREATE_RECORD = 306,
    UNABLE_TO_DELETE_RECORD = 307,
    UNABLE_TO_CREATE_OR_UPDATE_RECORD = 308,
    CONFLICT_OPERATION = 309,
    INVALID_DATABASE_OPERATION = 310,

    // Errores de API y Recursos (400-499)
    GENERAL_API_ERROR = 400,
    RESOURCE_NOT_FOUND = 401,
    METHOD_NOT_SUPPORTED = 402,
    RATE_LIMIT_EXCEEDED = 403,
    UNABLE_TO_HAS_DATA = 404,

    // Errores de Servicios Externos (500-599)
    GENERAL_EXTERNAL_SERVICE_ERROR = 500,
    EXTERNAL_SERVICE_UNAVAILABLE = 501,
    EXTERNAL_SERVICE_TIMEOUT = 502,
    EXTERNAL_SERVICE_ERROR = 503,
}